# -*- coding: utf-8 -*-

# !pip install tiktoken langchain openai chromadb gspread oauth2client nltk pydantic == 1.10.8

class draft03_protask():
    def __init__(self):
        pass

    def run(self, msg):
        """ДЗ Pro | 3 занятие | Курс по дообучению | Гарант.ipynb

        Automatically generated by Colaboratory.

        Original file is located at
            https://colab.research.google.com/drive/abcdefgh

        Возьмите в интернете любую инструкцию по эксплуатации и на ее основе сделайте базу знаний для ответа на вопросы по этой инструкции. Для этого разбейте взятую инструкцию на логические блоки (как в занятии), и уже эти логические блоки разбейте сплиттерами на чанки. Создайте нейро-консультанта по данной базе знаний - с поддержанием диалога или без такового - на ваше усмотрение. Проверьте работу созданного нейро-консультанта.
        """

        # @title Установка библиотек

        # @title Импорт библиотек
        import gdown
        from langchain.llms import OpenAI
        from langchain.docstore.document import Document
        import requests
        from langchain.embeddings.openai import OpenAIEmbeddings
        from langchain.vectorstores import Chroma
        from langchain.text_splitter import RecursiveCharacterTextSplitter
        from langchain.prompts import PromptTemplate
        import pathlib
        import subprocess
        import tempfile
        import ipywidgets as widgets
        import os
        import gspread
        from oauth2client.service_account import ServiceAccountCredentials
        import re
        import getpass
        import os
        import openai
        import tiktoken

        # Получение ключа API от пользователя и установка его как переменной окружения
        openai_key = getpass.getpass("OpenAI API Key:")
        os.environ["OPENAI_API_KEY"] = openai_key
        openai.api_key = openai_key


if __name__ == '__main__':
    draft03_protask().run("")